"use strict";

/** @type {import('sequelize-cli').Migration} */
import { QueryInterface } from 'sequelize';

module.exports = {
  async up(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.bulkInsert(
      "States",
      [
        {
          name: "Alabama",
          code: "AL",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Alaska",
          code: "AK",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Arizona",
          code: "AZ",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Arkansas",
          code: "AR",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "California",
          code: "CA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Colorado",
          code: "CO",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Connecticut",
          code: "CT",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Delaware",
          code: "DE",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Florida",
          code: "FL",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Georgia",
          code: "GA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Hawaii",
          code: "HI",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Idaho",
          code: "ID",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Illinois",
          code: "IL",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Indiana",
          code: "IN",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Iowa",
          code: "IA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Kansas",
          code: "KS",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Kentucky",
          code: "KY",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Louisiana",
          code: "LA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Maine",
          code: "ME",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Maryland",
          code: "MD",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Massachusetts",
          code: "MA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Michigan",
          code: "MI",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Minnesota",
          code: "MN",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Mississippi",
          code: "MS",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Missouri",
          code: "MO",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Montana",
          code: "MT",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Nebraska",
          code: "NE",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Nevada",
          code: "NV",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "New Hampshire",
          code: "NH",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "New Jersey",
          code: "NJ",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "New Mexico",
          code: "NM",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "New York",
          code: "NY",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "North Carolina",
          code: "NC",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "North Dakota",
          code: "ND",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Ohio",
          code: "OH",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Oklahoma",
          code: "OK",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Oregon",
          code: "OR",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Pennsylvania",
          code: "PA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Rhode Island",
          code: "RI",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "South Carolina",
          code: "SC",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "South Dakota",
          code: "SD",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Tennessee",
          code: "TN",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Texas",
          code: "TX",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Utah",
          code: "UT",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Vermont",
          code: "VT",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Virginia",
          code: "VA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Washington",
          code: "WA",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "West Virginia",
          code: "WV",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Wisconsin",
          code: "WI",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Wyoming",
          code: "WY",
          country: "US",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Alberta",
          code: "AB",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "British Columbia",
          code: "BC",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Manitoba",
          code: "MB",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "New Brunswick",
          code: "NB",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Newfoundland and Labrador",
          code: "NL",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Northwest Territories",
          code: "NT",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Nova Scotia",
          code: "NS",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Nunavut",
          code: "NU",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Ontario",
          code: "ON",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Prince Edward Island",
          code: "PE",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Quebec",
          code: "QC",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Saskatchewan",
          code: "SK",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Yukon",
          code: "YT",
          country: "CA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.bulkDelete("States", {}, {});
  },
};

