"use strict";

/** @type {import('sequelize-cli').Migration} */
import { QueryInterface } from "sequelize";

module.exports = {
  async up(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.bulkInsert(
      "Quotes",
      [
        {
          quoteId: "M-0001",
          type: "Quote",
          status: "Open",
          probability: "Pipeline",
          projectName: "600 Hwy 7 East, Toronto, ON",
          units: 2,
          value: 30133.15,
          customerName: "TK Elevator - Scarborough",
          contact: "Faris Maqdass",
          endContractor: "",
          salesPerson: "Michelle Connell",
          quoteBy: "Michelle Connell",
          creationDate: "2022-09-26",
          estAwardDate: null,
          nextFollowUp: null,
        },
        {
          quoteId: "M-0002",
          type: "Quote",
          status: "Open",
          probability: "Pipeline",
          projectName: "Hilton Dener City Center",
          units: 7,
          value: 22337.1,
          customerName: "Schindler - Lakewood, CO",
          contact: "Jaime Sanchez",
          endContractor: "",
          salesPerson: "Krista Dvorak",
          quoteBy: "Fatma Lolo",
          creationDate: "2022-09-26",
          estAwardDate: null,
          nextFollowUp: null,
        },
        {
          quoteId: "M-0003",
          type: "Quote",
          status: "Open",
          probability: "Pipeline",
          projectName: "315 Front Street, Toronto, ON",
          units: 8,
          value: 171406.7,
          customerName: "TK Elevator - Scarborough",
          contact: "Faris Maqdass",
          endContractor: "",
          salesPerson: "Irene",
          quoteBy: "Michelle Connell",
          creationDate: "2022-09-26",
          estAwardDate: null,
          nextFollowUp: null,
        },
        {
          quoteId: "E-1001",
          type: "Quote",
          status: "Open",
          probability: "Pipeline",
          projectName: "215 West 84th, NY",
          units: 3,
          value: 299593.05,
          customerName: "Vantage NY",
          contact: "",
          endContractor: "Liberty",
          salesPerson: "Jose",
          quoteBy: "Michelle Connell",
          creationDate: "2022-09-26",
          estAwardDate: null,
          nextFollowUp: null,
        },
        {
          quoteId: "E-1002",
          type: "Quote",
          status: "Open",
          probability: "Pipeline",
          projectName: "WARWICK MELROSE HOTEL",
          units: 3,
          value: 299593.05,
          customerName: "TK Elevator - Scarborough",
          contact: "",
          endContractor: "Liberty",
          salesPerson: "Irene",
          quoteBy: "Michelle Connell",
          creationDate: "2023-05-04",
          estAwardDate: null,
          nextFollowUp: null,
        },
        {
          quoteId: "V-0001",
          type: "Visit",
          status: "",
          probability: "",
          projectName: "",
          customerName: "Schindler - Lakewood, CO",
          salesPerson: "Krista Dvorak",
          creationDate: "2022-07-01",
        },
      ],
      {}
    );
  },

  async down(queryInterface: QueryInterface): Promise<void> {
    await queryInterface.bulkDelete("Quotes", {}, {});
  },
};
